config/routes.rb
Rails.application.routes.draw do

root to: "static_pages#home"
     
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/help'

  get 'static_pages/faq'

  get 'static_pages/blog'

   resources :doctors
  resources :reviews
  devise_for :users, controllers: {
    registrations:'users/registrations',
    sessions: 'users/sessions'
  }
   resources :qualifications
   resources :hospital_affiliations
   resources :profiles
   resources :time_schedules
   resources :appointments
   resources :doctor_specializations
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/qualification.rb
class Qualification < ApplicationRecord
  belongs_to :doctor
  validates :doctor_id, uniqueness: true
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :set_qualification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :doctor_authentication



  # before_action :doctor_authentication

  # GET /qualifications
  # GET /qualifications.json
  def index
    @qualifications = Qualification.all
  end

  # GET /qualifications/1
  # GET /qualifications/1.json
  def show
  end

  # GET /qualifications/new
  def new
    @qualification = Qualification.new
  end

  # GET /qualifications/1/edit
  def edit
  end

  # POST /qualifications
  # POST /qualifications.json
  def create
    @qualification = Qualification.new(qualification_params)
    @qualification.doctor_id = current_user.doctor.id

    respond_to do |format|
      if @qualification.save
        format.html { redirect_to @qualification, notice: 'Qualification was successfully created.' }
        format.json { render :show, status: :created, location: @qualification }
      else
        format.html { render :new }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualifications/1
  # PATCH/PUT /qualifications/1.json
  def update
    respond_to do |format|
      if @qualification.update(qualification_params)
        format.html { redirect_to @qualification, notice: 'Qualification was successfully updated.' }
        format.json { render :show, status: :ok, location: @qualification }
      else
        format.html { render :edit }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualifications/1
  # DELETE /qualifications/1.json
  def destroy
    @qualification.destroy
    respond_to do |format|
      format.html { redirect_to qualifications_url, notice: 'Qualification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualification
      @qualification = Qualification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualification_params
      params.require(:qualification).permit(:qualification_name, :institute_name, :language, :board_certification, :procurement_year )
    end

    # doctor verification to uplode the profile (qualification)
end

app/helpers/qualifications_helper.rb
module QualificationsHelper

end

app/views/qualifications/_form.html.erb
<%= form_for(qualification) do |f| %>
  <% if qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qualification.errors.count, "error") %> prohibited this qualification from being saved:</h2>

      <ul>
      <% qualification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
          <%= f.label :qualification_name %>
          <%= f.text_area :qualification_name, autofocus: true %>
          <%= f.label :procurement_year %><%= f.date_field :procurement_year %>
          <%= f.label :language %><%= f.text_field :language %><br>
          <%= f.label :institute_name %><%= f.text_field :institute_name %><br>
          <%= f.label :board_certification %><%= f.text_field :board_certification %><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/qualifications/edit.html.erb
<h1>Editing Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Show', @qualification %> |
<%= link_to 'Back', qualifications_path %>

app/views/qualifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qualifications</h1>

<table>
  <thead>
    <tr>
    <th>Qualification</th>
    <th>Procurement Year</th>
    <th>Language Used</th>
    <th>Institute Name</th>
    <th>Board Certificates</th>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @qualifications.each do |qualification| %>
      <tr>
      <td><%= qualification.qualification_name %>  </td>
      <td><%= qualification.procurement_year %>  </td>
      <td><%= qualification.language %>  </td>
      <td><%= qualification.institute_name %>  </td>
      <td><%= qualification.board_certification %>  </td>
        <td><%= link_to 'Show', qualification %></td>
        <td><%= link_to 'Edit', edit_qualification_path(qualification) %></td>
        <td><%= link_to 'Destroy', qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualification', new_qualification_path %>

app/views/qualifications/new.html.erb
<h1>New Qualification</h1>

<%= render 'form', qualification: @qualification %>

<%= link_to 'Back', qualifications_path %>

app/views/qualifications/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_qualification_path(@qualification) %> |
<%= link_to 'Back', qualifications_path %>