config/routes.rb
Rails.application.routes.draw do

root to: "static_pages#home"
     
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/help'

  get 'static_pages/faq'

  get 'static_pages/blog'

   resources :doctors
  resources :reviews
  devise_for :users, controllers: {
    registrations:'users/registrations',
    sessions: 'users/sessions'
  }
   resources :qualifications
   resources :hospital_affiliations
   resources :profiles
   resources :time_schedules
   resources :appointments
   resources :doctor_specializations
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor_specialization.rb
class DoctorSpecialization < ApplicationRecord
  has_many :doctor
  has_many :specializations
  
end

app/controllers/doctor_specializations_controller.rb
class DoctorSpecializationsController < ApplicationController
  before_action :set_doctor_specialization, only: [:show, :edit, :update, :destroy]

  # GET /doctor_specializations
  # GET /doctor_specializations.json
  def index
    @doctor_specializations = DoctorSpecialization.all
  end

  # GET /doctor_specializations/1
  # GET /doctor_specializations/1.json
  def show
  end

  # GET /doctor_specializations/new
  def new
    @doctor_specialization = DoctorSpecialization.new
  end

  # GET /doctor_specializations/1/edit
  def edit
  end

  # POST /doctor_specializations
  # POST /doctor_specializations.json
  def create
    @doctor_specialization = DoctorSpecialization.new(doctor_specialization_params)

    respond_to do |format|
      if @doctor_specialization.save
        format.html { redirect_to @doctor_specialization, notice: 'Doctor specialization was successfully created.' }
        format.json { render :show, status: :created, location: @doctor_specialization }
      else
        format.html { render :new }
        format.json { render json: @doctor_specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctor_specializations/1
  # PATCH/PUT /doctor_specializations/1.json
  def update
    respond_to do |format|
      if @doctor_specialization.update(doctor_specialization_params)
        format.html { redirect_to @doctor_specialization, notice: 'Doctor specialization was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor_specialization }
      else
        format.html { render :edit }
        format.json { render json: @doctor_specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctor_specializations/1
  # DELETE /doctor_specializations/1.json
  def destroy
    @doctor_specialization.destroy
    respond_to do |format|
      format.html { redirect_to doctor_specializations_url, notice: 'Doctor specialization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor_specialization
      @doctor_specialization = DoctorSpecialization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_specialization_params
      params.require(:doctor_specialization).permit(:name)
    end
end

app/helpers/doctor_specializations_helper.rb
module DoctorSpecializationsHelper
end

app/views/doctor_specializations/_form.html.erb
<%= form_for(doctor_specialization) do |f| %>
  <% if doctor_specialization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor_specialization.errors.count, "error") %> prohibited this doctor_specialization from being saved:</h2>

      <ul>
      <% doctor_specialization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctor_specializations/edit.html.erb
<h1>Editing Doctor Specialization</h1>

<%= render 'form', doctor_specialization: @doctor_specialization %>

<%= link_to 'Show', @doctor_specialization %> |
<%= link_to 'Back', doctor_specializations_path %>

app/views/doctor_specializations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctor Specializations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctor_specializations.each do |doctor_specialization| %>
      <tr>
        <td><%= doctor_specialization.name %></td>
        <td><%= link_to 'Show', doctor_specialization %></td>
        <td><%= link_to 'Edit', edit_doctor_specialization_path(doctor_specialization) %></td>
        <td><%= link_to 'Destroy', doctor_specialization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor Specialization', new_doctor_specialization_path %>

app/views/doctor_specializations/new.html.erb
<h1>New Doctor Specialization</h1>

<%= render 'form', doctor_specialization: @doctor_specialization %>

<%= link_to 'Back', doctor_specializations_path %>

app/views/doctor_specializations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor_specialization.name %>
</p>

<%= link_to 'Edit', edit_doctor_specialization_path(@doctor_specialization) %> |
<%= link_to 'Back', doctor_specializations_path %>