config/routes.rb
Rails.application.routes.draw do

root to: "static_pages#home"
     
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/help'

  get 'static_pages/faq'

  get 'static_pages/blog'

   resources :doctors
  resources :reviews
  devise_for :users, controllers: {
    registrations:'users/registrations',
    sessions: 'users/sessions'
  }
   resources :qualifications
   resources :hospital_affiliations
   resources :profiles
   resources :time_schedules
   resources :appointments
   resources :doctor_specializations
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	belongs_to :user
	validates_uniqueness_of :user_id
	has_many :reviews
	has_many :appointments
	has_many :time_schedules, dependent: :destroy
	has_many :hospital_affiliations, dependent: :destroy
	has_one :qualification, dependent: :destroy
	has_one :doctor_specializations, dependent: :destroy
	has_many :offices, dependent: :destroy
	has_attached_file :profile_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :profile_image, content_type: /\Aimage\/.*\z/
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  include DoctorsHelper
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :doctor, only: [:new, :create]
  before_action :doctor_authentication, except: [:show, :index]
  before_action :specific_user, only: [ :edit, :update, :destroy ]


  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.where(profile_confirmation: true) #views of the doc profile only if confirmed
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @appointment = Appointment.new
    @review = Review.new
    @reviews = @doctor.reviews
    @qualification = @doctor.qualification  
        if @doctor.reviews.blank?
          @average_review = 0
        else
           @average_review = (@doctor.reviews.average(:wait_time_rating) + @doctor.reviews.average(:bedside_manner_rating) + @doctor.reviews.average(:overall_rating))/3           
        end   
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new 
    @doctor_specializations = DoctorSpecialization.all  
  end

  # GET /doctors/1/edit
  def edit
    
  end

  # POST /doctors
  # POST /doctors.json
  def create
    # binding.pry
    @doctor = current_user.doctor.update_attributes(professional_statement: params[:doctor][:professional_statement], practicing_from: params[:doctor][:practicing_from], profile_image: params[:doctor][:profile_image], certificate_image: params[:doctor][:certificate_image], fax_number: params[:doctor][:fax_number])
    redirect_to doctors_path
    # respond_to do |format|
    #   if @doctor.save
    #     format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
    #     format.json { render :show, status: :created, location: @doctor }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @doctor.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private  


   def specific_user
     if session[:doctor_id] != @doctor.id
      flash[:notice] = "You are not the right user"
      redirect_to doctor_path(@doctor) 
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:professional_statement, :practicing_from, :profile_image, :certificate_image, :fax_number, :award )
    end

    
end

app/helpers/doctors_helper.rb
module DoctorsHelper
   def doctor
    # binding.pry
        if  current_user.user_type == "doctor" 
              flash[:notice] = "you r doctors"
             'doctor/new'

         else
          flash[:notice] = "you r patient"
          redirect_to root_path
        end
    end 
end

app/views/doctors/_form.html.erb
<%= form_for doctor, html: { multipart: true } do |f| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    
      <% end %>
      </ul>
    </div>
  <% end %>
          
<div id="doctor_testomonial">
  <div class="wrapper">
    <div class="holder">
      <div class="container">
        <div class="row text-center">
            <div class="actions">
               <div class="margin"><%= f.label :professional_statement, :class =>'label0' %><br><%= f.text_area :professional_statement, autofocus: true, :class => 'statement_pannel' %>
                </div>
                <div class="doctor_specialization">
                </div>
                <div class="practicing_from margin"><%= f.label :practicing_from , :class => 'label1'%><br><%= f.date_field :practicing_from, :class => 'date_pannel statement_pannel' %></div>
                <div class="profile_image margin" ><center><%= f.label :profile_image, :class => 'label2' %><%= f.file_field :profile_image, :class => 'image_pannel' %>
                <%= f.label :certificate_image, :class => 'label3' %><%= f.text_field :certificate_image %></center></div>
              
                <div class="fax_number margin"><%= f.label :fax_number, :class => 'label4' %><br><%= f.text_field :fax_number, :class => 'fax_pannel statement_pannel' %></div>
          </div>

            <%= f.submit :class => 'submit_btn' %>
        </div>
      </div>
    </div>
  </div>
</div>

  
<% end %>
<style type="text/css">
  #doctor_testomonial { background:url('/assets/element.jpg'); background-size:cover; position: relative; z-index: 1;  }
  #doctor_testomonial:before{ content:""; position:absolute; left:0; top:0; width:100%; height:100%; z-index: -1; background: rgba(51, 51, 51, 0.7); }
  .wrapper { display: table; width: 100%; height: 100vh; margin: 0px; }
  .holder { display: table-cell; vertical-align: middle; padding: 15px 0px; }
  .margin {margin-bottom: 20px; font-size: 20px; color: #ffffff; line-height: 40px;}
  .statement_pannel {    height: 100px; width: 425px;border-radius: 5px; color: black;}
  .actions {color: #ffffff;}
  .date_pannel {    height: 38px; width: 425px;  border-radius: 5px; color: #000000;}
  .iamge_pannel{  }
  .fax_pannel { height: 38px; width: 425px;border-radius: 5px;}
  .label0 {    margin-right: 202px; margin-bottom: 0px;}
  .label1{     margin-right: 276px; margin-bottom: 0px;  }
  .label2{  }
  .label3{  }
  .label4{ margin-right: 310px; margin-bottom: 0px;  }
  .submit_btn {  height: 35px;border-radius: 5px;width: 425px; padding: 0 10px; border: none; background: #ffffff;box-shadow: 1px 1px 5px 0 #0003DD; }
</style>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
      <td><%= doctor.professional_statement %>  </td>
      <td><%= doctor.practicing_from %></td>
      <td><%= image_tag doctor.profile_image.url(:thumb) %></td>
      <td><%= doctor.certificate_image %></td>
      <td><%= doctor.fax_number %></td>
        <td><%= link_to 'Show', doctor %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--

<% if !current_user.doctor.nil? %>
       <% if current_user.doctor.profile_confirmation === false %>
           <h1>Pending cha</h1>
         <% else %>
          <h1> succes</h1>
      <% end %>
<% end %>
 -->

app/views/doctors/new.html.erb
<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<p id="notice"><%= notice %></p>
<div id="doctor-show " >
	<div class="header">
		<div class="container">
			<div class="row">
				<div class="profile">
				<div class="col-md-3"></div>
				<div class="profile-image col-md-3">
				 	<tbody>
				      <tr>
				      <td><%= image_tag @doctor.profile_image.url(:medium), class: "img-circle", width: "140px", height: "140px" %></td>
					      <div class="doctor-interface">
						        <td><%= link_to 'Edit', edit_doctor_path(@doctor) %></td>
						        </td>
					      </div>
				      </tr>
				 	 </tbody>
				 	 <div class="average-review-rating" data-score=<%= @average_review %>></div>
				 </div>

			 	 </div>
			 	 <div id="doctor-name " class="col-md-6">
		 			<h2 style="font-weight: bolder;"><%= "Dr." + @doctor.user.first_name + " " + @doctor.user.Last_name%></h2>
		 			<h5>Dentist</h5> 
		 			


	<% if current_user.user_type == "patient" %>
	 <% #if (Review.where("doctor_id = ? AND user_id = ?", params[:id], current_user.id)).empty? %>	 
	<%= link_to "BOOK Appointment", new_appointment_path(doctor_id: @doctor.id), remote: true,  class: 'btn'%>   
	<%= link_to "Add Review", new_review_path(doctor_id: @doctor.id),
				remote: true,  class: 'btn sign-up' %>


<%#end %>
<% end %>
		 		</div>
			</div>
		 </div>
	</div>
</div>






<div class="Q-statement background-style ">	
<% if @doctor.qualification.nil? %>
	<h1>the qualification is nill</h1>	
	<% if current_user.user_type == "doctor" %>
	<%= link_to 'redirect to qualification form', new_qualification_path %>
	<% end %>
 <%else %>

<div class="container">
		<div class="qualification-header">Qualifications and Experience</div>
		<div class="qualifications">
			<div class="row">
			<div class="col-md-1"></div>
				<div class="col-md-2">
					Education
				</div>
				<div class="col-md-6">
					     <%= @qualification.qualification_name %>
				</div>
			<div class="col-md-3"></div>
			</div>
			<hr class="qualifaction-divider">
			<div class="row">
			<div class="col-md-1"></div>
				<div class="col-md-2">
					Board Certificates
				</div>
				<div class="col-md-6">
									 <%= @qualification.board_certification %> 
				</div>
			<div class="col-md-3"></div>
			</div>
			<hr class="qualifaction-divider">
			<div class="row">
			<div class="col-md-1"></div>
				<div class="col-md-2">
					Specialities
				</div>
				<div class="col-md-6">
				 */*/*/***************
				</div>
			<div class="col-md-3"></div>
			</div>
			<hr class="qualifaction-divider">
			<div class="row">
			<div class="col-md-1"></div>
				<div class="col-md-2">
					Language
				</div>
				<div class="col-md-6">
				 <%= @qualification.language %> 
				</div>
			<div class="col-md-3"></div>	
			</div>
			<hr class="qualifaction-divider">
			<div class="row">
			<div class="col-md-1"></div>
				<div class="col-md-2">
					Institude Name
				</div>
				<div class="col-md-6">
					<%= @qualification.institute_name %> 
				</div>
			<div class="col-md-3"></div>	
			</div>
			<hr class="qualifaction-divider">
			<div class="row">
			<div class="col-md-1"></div>
				<div class="col-md-2">
					procurement year
				</div>
				<div class="col-md-6">
				<%= @qualification.procurement_year %>
				</div>
			<div class="col-md-3"></div>
			</div>
			<hr class="qualifaction-divider">
			<div class="row">
			<div class="col-md-1"></div>
				<div class="col-md-2">
					Contact
				</div>
				<div class="col-md-6">
				<%= @doctor.fax_number %>
				</div>
			<div class="col-md-3"></div>
			</div>
			<hr class="qualifaction-divider">
			<div class="row">
			<div class="col-md-1"></div>
				<div class="col-md-2">
					Proffessional statement
				</div>
				<div class="col-md-6">
				<%= @doctor.professional_statement%>
				</div>
			<div class="col-md-3"></div>
			</div>
			     <%= link_to 'Show', @qualification %>
				 <%= link_to 'Edit', edit_qualification_path(@qualification) %>
				 <%= link_to 'Destroy', @qualification, method: :delete, data: { confirm: 'Are you sure?' } %>
		</div>
	</div>
</div>


<% end %>

	<!-- review given by the users -->
<div id="review">
	<div class="user-rating">
		<div class="container doctor_review">
			<% @reviews.each do |review| %>
				<div class="row" id="review-<%= review.id%>">
					<div class="col-md-1"></div>
					<div class="col-md-2">
						Date of comment<br>
						by Sarvottam Hengaju<br>
						(verified patient)
					</div>
					<div class="col-md-2">
						Overall Rating<br>
						Bedside Manner Rating<br>
						Wait Time Rating
					</div>
					<div class="col-md-2">
						<div class="review-rating" data-score="<%= review.wait_time_rating %>"></div>
						<div class="review-rating" data-score="<%= review.bedside_manner_rating %>"></div>
						<div class="review-rating" data-score="<%= review.overall_rating %>"></div>
					</div>
					<div class="col-md-5">
						<label>Review:</label>
						<%= review.review %>
					</div>

					<%= link_to 'Show', review %>
		        <%= link_to 'Edit', edit_review_path(review), remote: true  %>
		        <%= link_to 'Destroy', review, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
				<hr>

				</div>
							<% end %>
		</div>
	</div>
</div>

</body>
</html>

<div id="review-modal" class="modal fade"></div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>