config/routes.rb
Rails.application.routes.draw do

root to: "static_pages#home"
     
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/help'

  get 'static_pages/faq'

  get 'static_pages/blog'

   resources :doctors
  resources :reviews
  devise_for :users, controllers: {
    registrations:'users/registrations',
    sessions: 'users/sessions'
  }
   resources :qualifications
   resources :hospital_affiliations
   resources :profiles
   resources :time_schedules
   resources :appointments
   resources :doctor_specializations
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hospital_affiliation.rb
class HospitalAffiliation < ApplicationRecord
  belongs_to :doctor
  has_many :time_schedules
  has_many :offices


end

app/controllers/hospital_affiliations_controller.rb
class HospitalAffiliationsController < ApplicationController
  before_action :set_hospital_affiliation, only: [:show, :edit, :update, :destroy]
   before_action :doctor_authentication, except: [:index]

  # GET /hospital_affiliations
  # GET /hospital_affiliations.json
  def index
    @hospital_affiliations = HospitalAffiliation.all
  end

  # GET /hospital_affiliations/1
  # GET /hospital_affiliations/1.json
  def show
  end

  # GET /hospital_affiliations/new
  def new
    @hospital_affiliation = HospitalAffiliation.new
  end

  # GET /hospital_affiliations/1/edit
  def edit
  end

  # POST /hospital_affiliations
  # POST /hospital_affiliations.json
  def create
  
    @hospital_affiliation = HospitalAffiliation.new(hospital_affiliation_params)
    @hospital_affiliation.doctor_id = current_user.doctor.id

    respond_to do |format|
      if @hospital_affiliation.save
        format.html { redirect_to @hospital_affiliation, notice: 'Hospital affiliation was successfully created.' }
        format.json { render :show, status: :created, location: @hospital_affiliation }
      else
        format.html { render :new }
        format.json { render json: @hospital_affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospital_affiliations/1
  # PATCH/PUT /hospital_affiliations/1.json
  def update
    respond_to do |format|
      if @hospital_affiliation.update(hospital_affiliation_params)
        format.html { redirect_to @hospital_affiliation, notice: 'Hospital affiliation was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital_affiliation }
      else
        format.html { render :edit }
        format.json { render json: @hospital_affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospital_affiliations/1
  # DELETE /hospital_affiliations/1.json
  def destroy
    @hospital_affiliation.destroy
    respond_to do |format|
      format.html { redirect_to hospital_affiliations_url, notice: 'Hospital affiliation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital_affiliation
      @hospital_affiliation = HospitalAffiliation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_affiliation_params
            params.require(:hospital_affiliation).permit(:affiliation, :city, :country, :start_date, :contact, :address )
    end

end

app/helpers/hospital_affiliations_helper.rb
module HospitalAffiliationsHelper
	# def fast
 #      if current_user.doctor.nil?
 #          redirect_to new_doctor_path
 #      end
 #    end
end

app/views/hospital_affiliations/_form.html.erb
<%= form_for(hospital_affiliation) do |f| %>
  <% if hospital_affiliation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital_affiliation.errors.count, "error") %> prohibited this hospital_affiliation from being saved:</h2>

      <ul>
      <% hospital_affiliation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
  <%= f.label :affiliation %>
          <%= f.text_field :affiliation, autofocus: true %>
          <%= f.label :city %><%= f.text_field :city %>
          <%= f.label :country %><%= f.text_field :country %><br>
          <%= f.label :start_date %><%= f.date_field :start_date %><br>
          <%= f.label :contact %><%= f.text_field :contact %><br>
          streat<%= f.label :address %><%= f.text_field :address %><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/hospital_affiliations/edit.html.erb
<h1>Editing Hospital Affiliation</h1>

<%= render 'form', hospital_affiliation: @hospital_affiliation %>

<%= link_to 'Show', @hospital_affiliation %> |
<%= link_to 'Back', hospital_affiliations_path %>

app/views/hospital_affiliations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospital Affiliations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospital_affiliations.each do |hospital_affiliation| %>
      <tr>
        <td><%= link_to 'Show', hospital_affiliation %></td>
        <td><%= link_to 'Edit', edit_hospital_affiliation_path(hospital_affiliation) %></td>
        <td><%= link_to 'Destroy', hospital_affiliation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital Affiliation', new_hospital_affiliation_path %>

app/views/hospital_affiliations/new.html.erb
<h1>New Hospital Affiliation</h1>

<%= render 'form', hospital_affiliation: @hospital_affiliation %>

<%= link_to 'Back', hospital_affiliations_path %>

app/views/hospital_affiliations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hospital_affiliation_path(@hospital_affiliation) %> |
<%= link_to 'Back', hospital_affiliations_path %>